#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)


#
# Load global settings
#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  if [ "$(ls -A /etc/X11/xinit/xinitrc.d)" ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
      [ -x "$f" ] && . "$f"
    done
    unset f
  fi
fi


#
# export extra PATHs
#
for f in /opt/*; do
    if [ `basename $f` != lost+found ]; then
        if [ -d $f ]; then
            highest=`ls $f | cat | sort -V | tail -n1`
            if [ $highest != "" ]; then
                export PATH=$PATH:$f/$highest/bin
            fi
        fi
    fi
done


#
# ibus input method
#
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS="@im=ibus"
ibus-daemon -drx


#
# Close X by Ctrl + Alt + Backspace
#
setxkbmap -option terminate:ctrl_alt_bksp


#
# Load resources and modmap
#
resources=$HOME/.config/xorg/Xresources
modmap=$HOME/.config/xorg/Xmodmap

[[ -f $resources ]] && xrdb -merge $resources
[[ -f $modmap ]] && xmodmap $modmap

#
# Switch left & right mouse button, and
# scroll directions
#
xmodmap -e "pointer = 3 2 1 4 5"

#
# Switch key(`~) and key(\|), make the Filco
# Minila Air keyboard consistent with HHKB
#
xmodmap -e "keycode 49 = backslash bar"
xmodmap -e "keycode 51 = grave asciitilde"


#
# Some daemon processes
#
xcompmgr -C &
urxvtd -q -o -f &


#
# Show battery icon
#
cbatticon 0 &
cbatticon 1 &


#
# Start window manager
#
exec i3

