#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)


#
# Load global settings
#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


#
# Close X by Ctrl + Alt + Backspace
#
setxkbmap -option terminate:ctrl_alt_bksp


#
# Load resources and modmap
#
resources=$XDG_CONFIG_HOME/xorg/Xresources
modmap=$XDG_CONFIG_HOME/xorg/Xmodmap

[[ -f $resources ]] && xrdb -merge $resources
[[ -f $modmap ]] && xmodmap $modmap


#
# Start window manager
#
exec i3

