#
# ZSH configuration
#


# Environment variables
source "$HOME/.config/zsh/exports"

if [ ! -n "$ZSH" ]; then
  ZSH="$HOME/.config/zsh/oh-my-zsh"
fi

if [ ! -n "$ZSH_COMPDUMP" ]; then
    ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"
fi

# mkdir for zsh cache
zsh_cache=$HOME/.cache/zsh
if [ -n "$XDG_CACHE_HOME" ]; then
    zsh_cache=$XDG_CACHE_HOME/zsh
fi
mkdir -p $zsh_cache
unset zsh_cache

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="af-magic"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git svn)

source $ZSH/oh-my-zsh.sh

################################################################################

# History file configuration
HISTFILE=$XDG_CACHE_HOME/zsh/zsh_history
HISTSIZE=7000
SAVEHIST=7000

# Auto change directory if a path inputted instead of a command
setopt autocd

# Set emacs like key binding
bindkey -e

# Execute in background
{
   # Compile the completion dump to increase startup speed
   dump_file="$ZSH_COMPDUMP"
   if [[ "$dump_file" -nt "${dump_file}.zwc" || ! -s "${dump_file}.zwc" ]]; then
      zcompile "$dump_file"
   fi
} &!

# Aliases
source "$XDG_CONFIG_HOME/zsh/aliases"
